import iso639, copy



EDGE_TTS_DICT = {
    "af": ["af-ZA-AdriNeural", "af-ZA-WillemNeural"],
    "am": ["am-ET-AmehaNeural", "am-ET-MekdesNeural"],
    "ar": [
        "ar-AE-FatimaNeural",
        "ar-AE-HamdanNeural",
        "ar-BH-AliNeural",
        "ar-BH-LailaNeural",
        "ar-DZ-AminaNeural",
        "ar-DZ-IsmaelNeural",
        "ar-EG-SalmaNeural",
        "ar-EG-ShakirNeural",
        "ar-IQ-BasselNeural",
        "ar-IQ-RanaNeural",
        "ar-JO-SanaNeural",
        "ar-JO-TaimNeural",
        "ar-KW-FahedNeural",
        "ar-KW-NouraNeural",
        "ar-LB-LaylaNeural",
        "ar-LB-RamiNeural",
        "ar-LY-ImanNeural",
        "ar-LY-OmarNeural",
        "ar-MA-JamalNeural",
        "ar-MA-MounaNeural",
        "ar-OM-AbdullahNeural",
        "ar-OM-AyshaNeural",
        "ar-QA-AmalNeural",
        "ar-QA-MoazNeural",
        "ar-SA-HamedNeural",
        "ar-SA-ZariyahNeural",
        "ar-SY-AmanyNeural",
        "ar-SY-LaithNeural",
        "ar-TN-HediNeural",
        "ar-TN-ReemNeural",
        "ar-YE-MaryamNeural",
        "ar-YE-SalehNeural",
    ],
    "az": ["az-AZ-BabekNeural", "az-AZ-BanuNeural"],
    "bg": ["bg-BG-BorislavNeural", "bg-BG-KalinaNeural"],
    "bn": [
        "bn-BD-NabanitaNeural",
        "bn-BD-PradeepNeural",
        "bn-IN-BashkarNeural",
        "bn-IN-TanishaaNeural",
    ],
    "bs": ["bs-BA-GoranNeural", "bs-BA-VesnaNeural"],
    "ca": ["ca-ES-EnricNeural", "ca-ES-JoanaNeural"],
    "cs": ["cs-CZ-AntoninNeural", "cs-CZ-VlastaNeural"],
    "cy": ["cy-GB-AledNeural", "cy-GB-NiaNeural"],
    "da": ["da-DK-ChristelNeural", "da-DK-JeppeNeural"],
    "de": [
        "de-AT-IngridNeural",
        "de-AT-JonasNeural",
        "de-CH-JanNeural",
        "de-CH-LeniNeural",
        "de-DE-AmalaNeural",
        "de-DE-ConradNeural",
        "de-DE-KatjaNeural",
        "de-DE-KillianNeural",
    ],
    "el": ["el-GR-AthinaNeural", "el-GR-NestorasNeural"],
    "en": [
        "en-AU-NatashaNeural",
        "en-AU-WilliamNeural",
        "en-CA-ClaraNeural",
        "en-CA-LiamNeural",
        "en-GB-LibbyNeural",
        "en-GB-MaisieNeural",
        "en-GB-RyanNeural",
        "en-GB-SoniaNeural",
        "en-GB-ThomasNeural",
        "en-HK-SamNeural",
        "en-HK-YanNeural",
        "en-IE-ConnorNeural",
        "en-IE-EmilyNeural",
        "en-IN-NeerjaExpressiveNeural",
        "en-IN-NeerjaNeural",
        "en-IN-PrabhatNeural",
        "en-KE-AsiliaNeural",
        "en-KE-ChilembaNeural",
        "en-NG-AbeoNeural",
        "en-NG-EzinneNeural",
        "en-NZ-MitchellNeural",
        "en-NZ-MollyNeural",
        "en-PH-JamesNeural",
        "en-PH-RosaNeural",
        "en-SG-LunaNeural",
        "en-SG-WayneNeural",
        "en-TZ-ElimuNeural",
        "en-TZ-ImaniNeural",
        "en-US-AnaNeural",
        "en-US-AriaNeural",
        "en-US-ChristopherNeural",
        "en-US-EricNeural",
        "en-US-GuyNeural",
        "en-US-JennyNeural",
        "en-US-MichelleNeural",
        "en-US-RogerNeural",
        "en-US-SteffanNeural",
        "en-ZA-LeahNeural",
        "en-ZA-LukeNeural",
    ],
    "es": [
        "es-AR-ElenaNeural",
        "es-AR-TomasNeural",
        "es-BO-MarceloNeural",
        "es-BO-SofiaNeural",
        "es-CL-CatalinaNeural",
        "es-CL-LorenzoNeural",
        "es-CO-GonzaloNeural",
        "es-CO-SalomeNeural",
        "es-CR-JuanNeural",
        "es-CR-MariaNeural",
        "es-CU-BelkysNeural",
        "es-CU-ManuelNeural",
        "es-DO-EmilioNeural",
        "es-DO-RamonaNeural",
        "es-EC-AndreaNeural",
        "es-EC-LuisNeural",
        "es-ES-AlvaroNeural",
        "es-ES-ElviraNeural",
        "es-GQ-JavierNeural",
        "es-GQ-TeresaNeural",
        "es-GT-AndresNeural",
        "es-GT-MartaNeural",
        "es-HN-CarlosNeural",
        "es-HN-KarlaNeural",
        "es-MX-DaliaNeural",
        "es-MX-JorgeNeural",
        "es-NI-FedericoNeural",
        "es-NI-YolandaNeural",
        "es-PA-MargaritaNeural",
        "es-PA-RobertoNeural",
        "es-PE-AlexNeural",
        "es-PE-CamilaNeural",
        "es-PR-KarinaNeural",
        "es-PR-VictorNeural",
        "es-PY-MarioNeural",
        "es-PY-TaniaNeural",
        "es-SV-LorenaNeural",
        "es-SV-RodrigoNeural",
        "es-US-AlonsoNeural",
        "es-US-PalomaNeural",
        "es-UY-MateoNeural",
        "es-UY-ValentinaNeural",
        "es-VE-PaolaNeural",
        "es-VE-SebastianNeural",
    ],
    "et": ["et-EE-AnuNeural", "et-EE-KertNeural"],
    "fa": ["fa-IR-DilaraNeural", "fa-IR-FaridNeural"],
    "fi": ["fi-FI-HarriNeural", "fi-FI-NooraNeural"],
    "fil": ["fil-PH-AngeloNeural", "fil-PH-BlessicaNeural"],
    "fr": [
        "fr-BE-CharlineNeural",
        "fr-BE-GerardNeural",
        "fr-CA-AntoineNeural",
        "fr-CA-JeanNeural",
        "fr-CA-SylvieNeural",
        "fr-CH-ArianeNeural",
        "fr-CH-FabriceNeural",
        "fr-FR-DeniseNeural",
        "fr-FR-EloiseNeural",
        "fr-FR-HenriNeural",
    ],
    "ga": ["ga-IE-ColmNeural", "ga-IE-OrlaNeural"],
    "gl": ["gl-ES-RoiNeural", "gl-ES-SabelaNeural"],
    "gu": ["gu-IN-DhwaniNeural", "gu-IN-NiranjanNeural"],
    "he": ["he-IL-AvriNeural", "he-IL-HilaNeural"],
    "hi": ["hi-IN-MadhurNeural", "hi-IN-SwaraNeural"],
    "hr": ["hr-HR-GabrijelaNeural", "hr-HR-SreckoNeural"],
    "hu": ["hu-HU-NoemiNeural", "hu-HU-TamasNeural"],
    "id": ["id-ID-ArdiNeural", "id-ID-GadisNeural"],
    "is": ["is-IS-GudrunNeural", "is-IS-GunnarNeural"],
    "it": ["it-IT-DiegoNeural", "it-IT-ElsaNeural", "it-IT-IsabellaNeural"],
    "ja": ["ja-JP-KeitaNeural", "ja-JP-NanamiNeural"],
    "jv": ["jv-ID-DimasNeural", "jv-ID-SitiNeural"],
    "ka": ["ka-GE-EkaNeural", "ka-GE-GiorgiNeural"],
    "kk": ["kk-KZ-AigulNeural", "kk-KZ-DauletNeural"],
    "km": ["km-KH-PisethNeural", "km-KH-SreymomNeural"],
    "kn": ["kn-IN-GaganNeural", "kn-IN-SapnaNeural"],
    "ko": ["ko-KR-InJoonNeural", "ko-KR-SunHiNeural"],
    "lo": ["lo-LA-ChanthavongNeural", "lo-LA-KeomanyNeural"],
    "lt": ["lt-LT-LeonasNeural", "lt-LT-OnaNeural"],
    "lv": ["lv-LV-EveritaNeural", "lv-LV-NilsNeural"],
    "mk": ["mk-MK-AleksandarNeural", "mk-MK-MarijaNeural"],
    "ml": ["ml-IN-MidhunNeural", "ml-IN-SobhanaNeural"],
    "mn": ["mn-MN-BataaNeural", "mn-MN-YesuiNeural"],
    "mr": ["mr-IN-AarohiNeural", "mr-IN-ManoharNeural"],
    "ms": ["ms-MY-OsmanNeural", "ms-MY-YasminNeural"],
    "mt": ["mt-MT-GraceNeural", "mt-MT-JosephNeural"],
    "my": ["my-MM-NilarNeural", "my-MM-ThihaNeural"],
    "nb": ["nb-NO-FinnNeural", "nb-NO-PernilleNeural"],
    "ne": ["ne-NP-HemkalaNeural", "ne-NP-SagarNeural"],
    "nl": [
        "nl-BE-ArnaudNeural",
        "nl-BE-DenaNeural",
        "nl-NL-ColetteNeural",
        "nl-NL-FennaNeural",
        "nl-NL-MaartenNeural",
    ],
    "pl": ["pl-PL-MarekNeural", "pl-PL-ZofiaNeural"],
    "ps": ["ps-AF-GulNawazNeural", "ps-AF-LatifaNeural"],
    "pt": [
        "pt-BR-AntonioNeural",
        "pt-BR-FranciscaNeural",
        "pt-PT-DuarteNeural",
        "pt-PT-RaquelNeural",
    ],
    "ro": ["ro-RO-AlinaNeural", "ro-RO-EmilNeural"],
    "ru": ["ru-RU-DmitryNeural", "ru-RU-SvetlanaNeural"],
    "si": ["si-LK-SameeraNeural", "si-LK-ThiliniNeural"],
    "sk": ["sk-SK-LukasNeural", "sk-SK-ViktoriaNeural"],
    "sl": ["sl-SI-PetraNeural", "sl-SI-RokNeural"],
    "so": ["so-SO-MuuseNeural", "so-SO-UbaxNeural"],
    "sq": ["sq-AL-AnilaNeural", "sq-AL-IlirNeural"],
    "sr": ["sr-RS-NicholasNeural", "sr-RS-SophieNeural"],
    "su": ["su-ID-JajangNeural", "su-ID-TutiNeural"],
    "sv": ["sv-SE-MattiasNeural", "sv-SE-SofieNeural"],
    "sw": [
        "sw-KE-RafikiNeural",
        "sw-KE-ZuriNeural",
        "sw-TZ-DaudiNeural",
        "sw-TZ-RehemaNeural",
    ],
    "ta": [
        "ta-IN-PallaviNeural",
        "ta-IN-ValluvarNeural",
        "ta-LK-KumarNeural",
        "ta-LK-SaranyaNeural",
        "ta-MY-KaniNeural",
        "ta-MY-SuryaNeural",
        "ta-SG-AnbuNeural",
        "ta-SG-VenbaNeural",
    ],
    "te": ["te-IN-MohanNeural", "te-IN-ShrutiNeural"],
    "th": ["th-TH-NiwatNeural", "th-TH-PremwadeeNeural"],
    "tr": ["tr-TR-AhmetNeural", "tr-TR-EmelNeural"],
    "uk": ["uk-UA-OstapNeural", "uk-UA-PolinaNeural"],
    "ur": [
        "ur-IN-GulNeural",
        "ur-IN-SalmanNeural",
        "ur-PK-AsadNeural",
        "ur-PK-UzmaNeural",
    ],
    "uz": ["uz-UZ-MadinaNeural", "uz-UZ-SardorNeural"],
    "vi": ["vi-VN-HoaiMyNeural", "vi-VN-NamMinhNeural"],
    "zh": [
        "zh-CN-XiaoxiaoNeural",
        "zh-CN-XiaoyiNeural",
        "zh-CN-YunjianNeural",
        "zh-CN-YunxiNeural",
        "zh-CN-YunxiaNeural",
        "zh-CN-YunyangNeural",
        "zh-CN-liaoning-XiaobeiNeural",
        "zh-CN-shaanxi-XiaoniNeural",
        "zh-HK-HiuGaaiNeural",
        "zh-HK-HiuMaanNeural",
        "zh-HK-WanLungNeural",
        "zh-TW-HsiaoChenNeural",
        "zh-TW-HsiaoYuNeural",
        "zh-TW-YunJheNeural",
    ],
    "zu": ["zu-ZA-ThandoNeural", "zu-ZA-ThembaNeural"],
}

language_list = []
for lang_code in EDGE_TTS_DICT:
    language = iso639.find(lang_code)['name']
    language = language.split(";")[0].split(",")[0]
    language_list.append(language)

language_list.sort()

def get_voice_list(language):
    lang_code = iso639.to_iso639_1(language)
    voice_list = copy.deepcopy(EDGE_TTS_DICT[lang_code])
    voice_list.insert(0, "Random")
    return voice_list
